

server:
  port: 8081

spring:
  application:
    name: subscription
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      password: none
  datasource:
    url: jdbc:postgresql://localhost:5432/scolaire
    username: postgres
    password: TMSMstela
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: false
#    fetch-registry: false


